'use client';

import {
  AlarmClock,
  Anchor,
  Baby,
  Bed,
  Beer,
  Bike,
  BookOpen,
  Bus,
  Cake,
  Camera,
  Candy,
  Car,
  Cat,
  ChefHat,
  Clapperboard,
  Cloud,
  Coffee,
  Compass,
  CookingPot,
  Crown,
  Dog,
  Dumbbell,
  Feather,
  Film,
  Flag,
  Flame,
  Flower2,
  Footprints,
  Gamepad2,
  Gem,
  Gift,
  Headphones,
  Heart,
  Home,
  IceCream,
  Laugh,
  Leaf,
  Mail,
  Map,
  MapPin,
  MessageCircle,
  Mic,
  Moon,
  Mountain,
  Music,
  Navigation,
  Paintbrush,
  Palette,
  PartyPopper,
  Phone,
  Pizza,
  Plane,
  Popcorn,
  Rainbow,
  Rocket,
  Salad,
  Ship,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smile,
  Snowflake,
  Sofa,
  Sparkles,
  Star,
  Sun,
  Sunset,
  Tent,
  Ticket,
  Train,
  TreePine,
  Trophy,
  Tv,
  Umbrella,
  User,
  Users,
  Utensils,
  Video,
  Waves,
  Wine,
  Zap,
} from 'lucide-react';

const ICON_COMPONENTS = {
  'alarm-clock': AlarmClock,
  anchor: Anchor,
  baby: Baby,
  bed: Bed,
  beer: Beer,
  bike: Bike,
  'book-open': BookOpen,
  bus: Bus,
  cake: Cake,
  camera: Camera,
  candy: Candy,
  car: Car,
  cat: Cat,
  'chef-hat': ChefHat,
  clapperboard: Clapperboard,
  cloud: Cloud,
  coffee: Coffee,
  compass: Compass,
  'cooking-pot': CookingPot,
  crown: Crown,
  dog: Dog,
  dumbbell: Dumbbell,
  feather: Feather,
  film: Film,
  flag: Flag,
  flame: Flame,
  'flower-2': Flower2,
  footprints: Footprints,
  'gamepad-2': Gamepad2,
  gem: Gem,
  gift: Gift,
  headphones: Headphones,
  heart: Heart,
  home: Home,
  'ice-cream': IceCream,
  laugh: Laugh,
  leaf: Leaf,
  mail: Mail,
  map: Map,
  'map-pin': MapPin,
  'message-circle': MessageCircle,
  mic: Mic,
  moon: Moon,
  mountain: Mountain,
  music: Music,
  navigation: Navigation,
  paintbrush: Paintbrush,
  palette: Palette,
  'party-popper': PartyPopper,
  phone: Phone,
  pizza: Pizza,
  plane: Plane,
  popcorn: Popcorn,
  rainbow: Rainbow,
  rocket: Rocket,
  salad: Salad,
  ship: Ship,
  shirt: Shirt,
  'shopping-bag': ShoppingBag,
  'shopping-cart': ShoppingCart,
  smile: Smile,
  snowflake: Snowflake,
  sofa: Sofa,
  sparkles: Sparkles,
  star: Star,
  sun: Sun,
  sunset: Sunset,
  tent: Tent,
  ticket: Ticket,
  train: Train,
  'tree-pine': TreePine,
  trophy: Trophy,
  tv: Tv,
  umbrella: Umbrella,
  user: User,
  users: Users,
  utensils: Utensils,
  video: Video,
  volleyball: Trophy,
  waves: Waves,
  wine: Wine,
  zap: Zap,
};

export default function LucideIcon({ name, fallback = 'sparkles', ...props }) {
  const Component = ICON_COMPONENTS[name] || ICON_COMPONENTS[fallback] || Sparkles;
  return <Component {...props} />;
}
